const root = 'https://whispering-depths-96388.herokuapp.com'
// const root = 'http://localhost:3000'
export const auth = `${root}/authenticate`
export const newUser = `${root}/users/new`
export const newTeam = `${root}/teams/new`
export const newChar = `${root}/characters/new`
export const delTeam = `${root}/character/`
export const userCrud = `${root}/user/`
export const teamCrud = `${root}/team/`
export const dungeons = `${root}/dungeons/`
export const floor = `${root}/floor/`
export const attack = `${root}/attack/`
export const hit = `${root}/hit/`
export const heal = `${root}/heal/`
export const save = `${root}/save/`
export const load = `${root}/load/`
export const randomTeam = `${root}/random/`
export const delSave= `${root}/save_delete/`